uplaoding the dataset

In [3]:
import pandas as pd
from google.colab import files
up=files.upload()

Saving India_GDP_1960-2022.csv to India_GDP_1960-2022.csv

In [4]:
import pandas as pd
import io
ind=pd.read_csv(io.BytesIO(up["India_GDP_1960-2022.csv"]),index_col=0)
ind

,India GDP - Historical Data,India GDP - Historical Data.1,India GDP - Historical Data.2,India GDP - Historical Data.3
NaN,Year,GDP in (Billion) $,Per Capita in rupees,Growth %
0.0,2021,3173.4,182160,8.95
1.0,2020,2667.69,154640,-6.6
2.0,2019,2831.55,165760,3.74
3.0,2018,2702.93,159840,6.45
...,...,...,...,...
57.0,1964,56.48,9280,7.45
58.0,1963,48.42,8080,5.99
59.0,1962,42.16,7200,2.93
60.0,1961,39.23,6800,3.72
61.0,1960,37.03,6560,0

In [5]:
ind.head(20)

,India GDP - Historical Data,India GDP - Historical Data.1,India GDP - Historical Data.2,India GDP - Historical Data.3
NaN,Year,GDP in (Billion) $,Per Capita in rupees,Growth %
0.0,2021,3173.4,182160,8.95
1.0,2020,2667.69,154640,-6.6
2.0,2019,2831.55,165760,3.74
3.0,2018,2702.93,159840,6.45
4.0,2017,2651.47,158480,6.8
5.0,2016,2294.8,138640,8.26
6.0,2015,2103.59,128480,8
7.0,2014,2039.13,125920,7.41
8.0,2013,1856.72,116000,6.39
9.0,2012,1827.64,115520,5.46
10.0,2011,1823.05,116640,5.24
11.0,2010,1675.62,108640,8.5
12.0,2009,1341.89,88160,7.86
13.0,2008,1198.9,79920,3.09
14.0,2007,1216.74,82240,7.66
15.0,2006,940.26,64560,8.06
16.0,2005,820.38,57200,7.92
17.0,2004,709.15,50240,7.92
18.0,2003,607.7,43760,7.86

In [6]:
ind.head()

,India GDP - Historical Data,India GDP - Historical Data.1,India GDP - Historical Data.2,India GDP - Historical Data.3
NaN,Year,GDP in (Billion) $,Per Capita in rupees,Growth %
0.0,2021,3173.4,182160,8.95
1.0,2020,2667.69,154640,-6.6
2.0,2019,2831.55,165760,3.74
3.0,2018,2702.93,159840,6.45

In [8]:
ind.tail()

,India GDP - Historical Data,India GDP - Historical Data.1,India GDP - Historical Data.2,India GDP - Historical Data.3
57.0,1964,56.48,9280,7.45
58.0,1963,48.42,8080,5.99
59.0,1962,42.16,7200,2.93
60.0,1961,39.23,6800,3.72
61.0,1960,37.03,6560,0

In [9]:
ind.tail(20)

,India GDP - Historical Data,India GDP - Historical Data.1,India GDP - Historical Data.2,India GDP - Historical Data.3
42.0,1979,152.99,17920,-5.24
43.0,1978,137.3,16480,5.71
44.0,1977,121.49,14880,7.25
45.0,1976,102.72,12880,1.66
46.0,1975,98.47,12640,9.15
47.0,1974,99.53,13040,1.19
48.0,1973,85.52,11520,3.3
49.0,1972,71.46,9840,-0.55
50.0,1971,67.35,9520,1.64
51.0,1970,62.42,8960,5.16
52.0,1969,58.45,8640,6.54
53.0,1968,53.09,8000,3.39
54.0,1967,50.13,7680,7.83
55.0,1966,45.87,7200,-0.06
56.0,1965,59.55,9520,-2.64
57.0,1964,56.48,9280,7.45
58.0,1963,48.42,8080,5.99
59.0,1962,42.16,7200,2.93
60.0,1961,39.23,6800,3.72
61.0,1960,37.03,6560,0

In [10]:
ind.info()

<class 'pandas.core.frame.DataFrame'>
Float64Index: 63 entries, nan to 61.0
Data columns (total 4 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   India GDP - Historical Data    63 non-null     object
 1   India GDP - Historical Data.1  63 non-null     object
 2   India GDP - Historical Data.2  63 non-null     object
 3   India GDP - Historical Data.3  63 non-null     object
dtypes: object(4)
memory usage: 2.5+ KB

In [11]:
ind.describe()

,India GDP - Historical Data,India GDP - Historical Data.1,India GDP - Historical Data.2,India GDP - Historical Data.3
count,63,63,63,63
unique,63,63,60,61
top,Year,GDP in (Billion) $,27680,7.86
freq,1,1,2,2